from transformers import AutoConfig
from gptqmodel.quantization.awq.models import *

AWQ_CAUSAL_LM_MODEL_MAP = {
    "mpt": MptAWQForCausalLM,
    "llama": LlamaAWQForCausalLM,
    "opt": OptAWQForCausalLM,
    "RefinedWeb": FalconAWQForCausalLM,
    "RefinedWebModel": FalconAWQForCausalLM,
    "exaone": ExaoneAWQForCausalLM,
    "falcon": FalconAWQForCausalLM,
    "bloom": BloomAWQForCausalLM,
    "gptj": GPTJAWQForCausalLM,
    "gpt_bigcode": GptBigCodeAWQForCausalLM,
    "mistral": MistralAWQForCausalLM,
    "mixtral": MixtralAWQForCausalLM,
    "gpt_neox": GPTNeoXAWQForCausalLM,
    "aquila": AquilaAWQForCausalLM,
    "Yi": YiAWQForCausalLM,
    "qwen": QwenAWQForCausalLM,
    "baichuan": BaichuanAWQForCausalLM,
    "llava": LlavaAWQForCausalLM,
    "qwen2": Qwen2AWQForCausalLM,
    "qwen3": Qwen3AWQForCausalLM,
    "qwen3_moe": Qwen3MoeAWQForCausalLM,
    "gemma": GemmaAWQForCausalLM,
    "gemma2": Gemma2AWQForCausalLM,
    "stablelm": StableLmAWQForCausalLM,
    "starcoder2": Starcoder2AWQForCausalLM,
    "llava_next": LlavaNextAWQForCausalLM,
    "phi3": Phi3AWQForCausalLM,
    "phi3_v": Phi3VAWQForCausalLM,
    "cohere": CohereAWQForCausalLM,
    "deepseek_v2": DeepseekV2AWQForCausalLM,
    "deepseek_v3": DeepseekV3AWQForCausalLM,
    "minicpm": MiniCPMAWQForCausalLM,
    "internlm2": InternLM2AWQForCausalLM,
    "minicpm3": MiniCPM3AWQForCausalLM,
    "qwen2_vl": Qwen2VLAWQForCausalLM,
    "qwen2_5_vl": Qwen2_5_VLAWQForCausalLM,
    "qwen2_5_omni": Qwen2_5_OmniAWQForConditionalGeneration
}
