common:
  - tokenicer
  - transformers
  - tabulate
  - swig # for models/tests

tests:
  test_awq_bitblas.py:
    - http://10.0.13.31/files/bitblas-0.1.0.post1+ubuntu.22.4.cu131-py3-none-any.whl

  test_bitblas.py:
    - http://10.0.13.31/files/bitblas-0.1.0.post1+ubuntu.22.4.cu131-py3-none-any.whl


  test_q4_bitblas.py:
    - http://10.0.13.31/files/bitblas-0.1.0.post1+ubuntu.22.4.cu131-py3-none-any.whl

  test_inference_speed.py:
    - http://10.0.13.31/files/bitblas-0.1.0.post1+ubuntu.22.4.cu131-py3-none-any.whl

  test_save_loaded_quantized_model.py:
    - http://10.0.13.31/files/bitblas-0.1.0.post1+ubuntu.22.4.cu131-py3-none-any.whl

  test_olora_finetuning_xpu.py:
    - intel_extension_for_pytorch
    - trl
    - wandb

  test_inference_result_xpu.py:
    - intel_extension_for_pytorch

  test_save_loaded_quantized_model_ipex.py:
    - intel_extension_for_pytorch

  test_torch_xpu.py:
    - intel_extension_for_pytorch

  test_q4_ipex.py:
    - intel_extension_for_pytorch

  test_mlx.py:
    - mlx_lm

  test_modelscope.py:
    - modelscope

  test_sglang.py:
    - transformers==4.48.3
    - numpy==1.26.3
    - sglang

  test_integration.py:
    - https://github.com/huggingface/transformers
    - https://github.com/huggingface/optimum

  test_awq_gemm.py:
    - peft

  test_awq_marlin.py:
    - peft

  test_awq_gemv.py:
    - peft

  test_awq_gemv_fast.py:
    - peft

  test_awq_llm_awq.py:
    - peft

  test_awq_inference_mistral.py:
    - peft

  test_awq_inference_llm_awq.py:
    - peft

  test_asym_gptq_v1.py:
    - peft

  test_bits.py:
    - peft

  test_lora.py:
    - peft

  test_mmlupro.py:
    - peft

  test_eval.py:
    - peft
    - http://10.0.13.31/files/evalplus-0.4.0.dev44-py3-none-any.whl
    - http://10.0.13.31/files/vllm-0.17.2rc1.dev52+g86b7e3c95.d20260318.cu131-cp313-cp313-linux_x86_64.whl
    - flashinfer-python==0.6.5

  test_evalplus.py:
    - http://10.0.13.31/files/evalplus-0.4.0.dev44-py3-none-any.whl

  test_nemotron_ultra.py:
    - http://10.0.13.31/files/causal_conv1d-1.6.0-cp313-cp313-linux_x86_64.whl

  test_openai_server.py:
    - openai
    - uvicorn
    - fastapi
    - pydantic

  test_local_model_paths.py:
    - gguf

tests/models:
  test_cohere2:
    - jieba

  test_gemma:
    - jieba

  test_bloom.py:
    - peft

  test_brumby.py:
    - retention

  test_hymba.py:
    - http://10.0.13.31/files/causal_conv1d-1.6.0-cp313-cp313-linux_x86_64.whl
    - mamba_ssm

  test_internlm.py:
    - transformers<=4.44.2

  test_ovis_1_6_llama.py:
    - transformers<=4.44.2

  test_phi_3_moe.py:
    - transformers<=4.44.2

tests/models/awq:
  test_qwen3_8b_base_awq.py:
    - peft
