common:
  py: 3.14t # common config
  gpu: 1

tests:
  test_multi_gpu_inference: # per-test config
    gpu: 5
    py: 3.14t

  test_calibration_data_device:
    gpu: 2
    py: 3.14t


tests/models:
  py: 3.13
