[build-system]
requires = ["setuptools >= 64",
    # same with requirements.txt
    "accelerate>=1.10.1" ,
    "numpy>=2.2.6" ,
    "torch>=2.8.0" ,
    "safetensors>=0.6.2" ,
    "transformers>=4.56.0" ,
    "threadpoolctl>=3.6.0" ,
    "packaging>=24.2" ,
    "device-smi==0.4.1" ,
    "protobuf>=6.32.0" ,
    "pillow>=11.3.0" ,
    "hf_transfer>=0.1.9" ,
    "huggingface_hub>=0.34.4" ,
    "random_word==1.0.13" ,
    "tokenicer>=0.0.5" ,
    "logbar==0.0.4" ,
    "wheel>=0.45.1" ,
    "maturin>=1.9.3" ,
]
build-backend = "setuptools.build_meta:__legacy__"
