# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
from __future__ import annotations

import argparse
import itertools
import os
import re
import sys
from pathlib import Path

import jinja2

try:
    import torch
except Exception:  # pragma: no cover - torch import depends on host env
    torch = None


FILE_HEAD_COMMENT = """
// auto generated by generate_kernels.py
// clang-format off
""".lstrip()

FILE_HEAD = (
    FILE_HEAD_COMMENT
    + """
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {
"""
)
FILE_TAIL = "}\n"

TEMPLATE = (
    "template __global__ void Marlin<"
    "{{a_type_id}}, "
    "{{b_type_id}}, "
    "{{c_type_id}}, "
    "{{s_type_id}}, "
    "{{threads}}, "
    "{{thread_m_blocks}}, "
    "{{thread_n_blocks}}, "
    "{{thread_k_blocks}}, "
    "{{m_block_size_8}}, "
    "{{stages}}, "
    "{{group_blocks}}, "
    "{{is_zp_float}}>"
    "( MARLIN_KERNEL_PARAMS );"
)

THREAD_CONFIGS = [(128, 128, 256), (64, 256, 256), (64, 128, 128), (128, 64, 128)]
THREAD_M_BLOCKS = [0.5, 1, 2, 3, 4]

QUANT_CONFIGS = [
    {
        "b_type": "kU4",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 2, 4, 8],
    },
    {
        "b_type": "kU4B8",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 0, 2, 4, 8],
    },
    {
        "b_type": "kU8B128",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 0, 2, 4, 8],
    },
    {
        "b_type": "kFE4M3fn",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 8],
    },
    {
        "b_type": "kFE2M1f",
        "s_type": "kFE4M3fn",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [1],
    },
    {
        "a_type": ["kBFloat16"],
        "b_type": "kFE2M1f",
        "s_type": "kFE8M0fnu",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [2],
    },
    {
        "a_type": ["kBFloat16"],
        "b_type": "kFE4M3fn",
        "s_type": "kFE8M0fnu",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [2],
    },
    {
        "a_type": ["kS8"],
        "b_type": "kU4",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    {
        "a_type": ["kS8"],
        "b_type": "kU4B8",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    {
        "a_type": ["kFE4M3fn"],
        "b_type": "kU4B8",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    {
        "a_type": ["kFE4M3fn"],
        "b_type": "kU4",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    {
        "a_type": ["kFE4M3fn"],
        "b_type": "kFE2M1f",
        "c_type": ["kBFloat16"],
        "s_type": "kFE8M0fnu",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [2],
    },
]

_ARCH_PATTERN = re.compile(r"(?:(?:sm|compute)_)?(\d+(?:\.\d+)?)")


def _is_4bit_weight(b_type: str) -> bool:
    return b_type in {"kU4", "kU4B8", "kFE2M1f"}


def _normalize_arch_token(token: str) -> int | None:
    cleaned = token.strip().lower().replace("+ptx", "")
    if not cleaned:
        return None
    match = _ARCH_PATTERN.fullmatch(cleaned)
    if not match:
        return None
    raw_value = match.group(1)
    if "." in raw_value:
        major_text, minor_text = raw_value.split(".", maxsplit=1)
        return int(major_text) * 10 + int(minor_text[:1] or "0")
    return int(raw_value)


def _detected_arch_tokens() -> list[str]:
    override = os.getenv("TORCH_CUDA_ARCH_LIST")
    if override:
        return [token for token in override.replace(";", ",").split(",") if token.strip()]

    if torch is not None and getattr(torch, "cuda", None) is not None:
        try:
            if torch.cuda.is_available():
                supported_sms = [
                    int(arch.split("_", maxsplit=1)[1].rstrip("af"))
                    for arch in torch.cuda.get_arch_list()
                    if arch.startswith("sm_")
                ]
                max_supported_sm = max(supported_sms) if supported_sms else None
                tokens = []
                for device_index in range(torch.cuda.device_count()):
                    major, minor = torch.cuda.get_device_capability(device_index)
                    capability = major * 10 + minor
                    if max_supported_sm is not None:
                        capability = min(capability, max_supported_sm)
                    tokens.append(f"{capability // 10}.{capability % 10}")
                if tokens:
                    return tokens
        except Exception:
            # Capability probing is best-effort here; fall back to the conservative
            # default arch list when the local CUDA runtime cannot be queried.
            pass

    return ["7.5", "8.0", "8.9"]


def resolve_arch_list(arch_list_text: str | None = None) -> tuple[int, ...]:
    tokens = arch_list_text.split(",") if arch_list_text else _detected_arch_tokens()
    arch_values = {
        normalized for token in tokens if (normalized := _normalize_arch_token(token)) is not None
    }
    if not arch_values:
        raise RuntimeError("No valid CUDA arch values were resolved for Marlin kernel generation.")
    return tuple(sorted(arch_values))


def remove_old_kernels(root: Path | None = None) -> None:
    root = root or Path(__file__).parent
    for path in root.glob("*kernel_*.cu"):
        path.unlink(missing_ok=True)
    (root / "kernel_selector.h").unlink(missing_ok=True)


def _kernel_file_name(prefix: str, a_type: str, b_type: str, c_type: str) -> str:
    return f"{prefix}_kernel_{a_type[1:]}_{b_type[1:]}_{c_type[1:]}".lower() + ".cu"


def _render_kernel_file_text(templates: list[str]) -> str:
    return FILE_HEAD + "\n\n" + "\n\n".join(templates) + "\n\n" + FILE_TAIL


def _build_expected_outputs(arch_list_text: str | None = None) -> tuple[dict[tuple[str, str], dict[Path, str]], str]:
    archs = resolve_arch_list(arch_list_text)
    support_fp8 = any(arch in {89, 120} for arch in archs)
    support_sm80 = any(arch >= 80 for arch in archs)
    support_sm75 = 75 in archs

    outputs: dict[tuple[str, str], dict[Path, str]] = {}
    kernel_selector_text = FILE_HEAD_COMMENT

    result_dict: dict[tuple[str, str, str], list[dict[str, object]]] = {}
    sm75_result_dict: dict[tuple[str, str, str], list[dict[str, object]]] = {}

    for quant_config in QUANT_CONFIGS:
        c_types = quant_config.get("c_type", ["kFloat16", "kBFloat16"])
        a_types = quant_config.get("a_type", ["kFloat16", "kBFloat16"])
        b_type = quant_config["b_type"]
        is_zp_float = quant_config.get("is_zp_float", False)
        all_group_blocks = quant_config["group_blocks"]
        all_m_blocks = quant_config["thread_m_blocks"]
        all_thread_configs = quant_config["thread_configs"]

        for a_type, c_type in itertools.product(a_types, c_types):
            if not support_fp8 and a_type == "kFE4M3fn":
                continue
            if "16" in a_type and "16" in c_type and a_type != c_type:
                continue

            s_type = quant_config.get("s_type", c_type)
            key = (a_type, b_type, c_type)
            result_dict.setdefault(key, [])
            if a_type in ["kFloat16", "kS8"] and c_type == "kFloat16":
                sm75_result_dict.setdefault(key, [])

            for group_blocks, m_blocks, thread_config in itertools.product(
                all_group_blocks, all_m_blocks, all_thread_configs
            ):
                thread_k, thread_n, threads = thread_config
                if threads == 256:
                    if m_blocks <= 1 and (thread_k, thread_n) != (128, 128):
                        continue
                    if m_blocks > 1 and (thread_k, thread_n) != (64, 256):
                        continue

                config = {
                    "threads": threads,
                    "s_type": s_type,
                    "thread_m_blocks": max(m_blocks, 1),
                    "thread_k_blocks": thread_k // 16,
                    "thread_n_blocks": thread_n // 16,
                    "m_block_size_8": "true" if m_blocks == 0.5 else "false",
                    "stages": 4,
                    "group_blocks": group_blocks,
                    "is_zp_float": "true" if is_zp_float else "false",
                }

                if support_sm80:
                    result_dict[key].append(config)
                if key in sm75_result_dict and support_sm75:
                    if _is_4bit_weight(b_type) and max(m_blocks, 1) * 2 > (thread_k // 16):
                        continue
                    config_sm75 = config.copy()
                    config_sm75["stages"] = 2
                    sm75_result_dict[key].append(config_sm75)

    for variant_name, configs_by_key in (("sm80", result_dict), ("sm75", sm75_result_dict)):
        for (a_type, b_type, c_type), config_list in configs_by_key.items():
            if not config_list:
                continue

            prefix = "sm89" if a_type == "kFE4M3fn" else variant_name
            templates: list[str] = []
            for config in config_list:
                s_type = str(config["s_type"])
                template_str = jinja2.Template(TEMPLATE).render(
                    a_type_id=f"vllm::{a_type}.id()",
                    b_type_id=f"vllm::{b_type}.id()",
                    c_type_id=f"vllm::{c_type}.id()",
                    s_type_id=f"vllm::{s_type}.id()",
                    **config,
                )
                templates.append(template_str)

                conditions = [
                    f"a_type == vllm::{a_type}",
                    f"b_type == vllm::{b_type}",
                    f"c_type == vllm::{c_type}",
                    f"s_type == vllm::{s_type}",
                    f"threads == {config['threads']}",
                    f"thread_m_blocks == {config['thread_m_blocks']}",
                    f"thread_n_blocks == {config['thread_n_blocks']}",
                    f"thread_k_blocks == {config['thread_k_blocks']}",
                    f"m_block_size_8 == {config['m_block_size_8']}",
                    f"stages == {config['stages']}",
                    f"group_blocks == {config['group_blocks']}",
                    f"is_zp_float == {config['is_zp_float']}",
                ]
                selector_prefix = "if" if kernel_selector_text == FILE_HEAD_COMMENT else "else if"
                kernel_selector_text += (
                    f"{selector_prefix} ({' && '.join(conditions)})\n"
                    f"  kernel = Marlin<"
                    f"vllm::{a_type}.id(), "
                    f"vllm::{b_type}.id(), "
                    f"vllm::{c_type}.id(), "
                    f"vllm::{s_type}.id(), "
                    f"{config['threads']}, "
                    f"{config['thread_m_blocks']}, "
                    f"{config['thread_n_blocks']}, "
                    f"{config['thread_k_blocks']}, "
                    f"{config['m_block_size_8']}, "
                    f"{config['stages']}, "
                    f"{config['group_blocks']}, "
                    f"{config['is_zp_float']}>;\n"
                )

            file_name = _kernel_file_name(prefix, a_type, b_type, c_type)
            outputs.setdefault((prefix, c_type), {})[Path(file_name)] = _render_kernel_file_text(templates)

    if not support_fp8 and kernel_selector_text != FILE_HEAD_COMMENT:
        kernel_selector_text += (
            "else if (a_type == vllm::kFE4M3fn)\n"
            '  TORCH_CHECK(false, "marlin kernel with fp8 activation is not built.");\n'
        )

    return outputs, kernel_selector_text


def build_expected_kernels(root: Path | None = None, arch_list_text: str | None = None) -> dict[Path, str]:
    root = root or Path(__file__).parent
    grouped_outputs, kernel_selector_text = _build_expected_outputs(arch_list_text)
    expected: dict[Path, str] = {}
    for outputs in grouped_outputs.values():
        for relative_path, rendered in outputs.items():
            expected[root / relative_path] = rendered
    expected[root / "kernel_selector.h"] = kernel_selector_text
    if len(expected) <= 1:
        raise RuntimeError("No Marlin kernels were generated; check the resolved CUDA arch list.")
    return expected


def generated_kernels_are_current(root: Path | None = None, arch_list_text: str | None = None) -> bool:
    root = root or Path(__file__).parent
    expected = build_expected_kernels(root, arch_list_text)
    expected_names = {path.name for path in expected}
    existing_names = {path.name for path in root.glob("*kernel_*.cu")}
    if (root / "kernel_selector.h").exists():
        existing_names.add("kernel_selector.h")
    if existing_names != expected_names:
        return False

    for output_path, expected_text in expected.items():
        try:
            current_text = output_path.read_text(encoding="utf-8")
        except OSError:
            return False
        if current_text != expected_text:
            return False
    return True


def generate_new_kernels(root: Path | None = None, arch_list_text: str | None = None) -> None:
    root = root or Path(__file__).parent
    expected = build_expected_kernels(root, arch_list_text)
    for path in root.glob("*kernel_*.cu"):
        if path not in expected:
            path.unlink(missing_ok=True)
    selector_path = root / "kernel_selector.h"
    if selector_path not in expected:
        selector_path.unlink(missing_ok=True)
    for output_path, rendered in expected.items():
        output_path.write_text(rendered, encoding="utf-8")


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Marlin CUDA kernel instantiation files.")
    parser.add_argument("--arch-list", default=None, help="Comma-separated CUDA arch list such as 8.0,8.9.")
    parser.add_argument("--check", action="store_true", help="Exit nonzero when generated files are stale.")
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = _parse_args(sys.argv[1:])
    if args.check:
        raise SystemExit(0 if generated_kernels_are_current(arch_list_text=args.arch_list) else 1)
    generate_new_kernels(arch_list_text=args.arch_list)
