// auto generated by generate_kernels.py
// clang-format off

#define MARLIN_KERNEL_FUNCTION MarlinEoraRank64
#define MARLIN_EORA_FUSED 1
#define MARLIN_EORA_RANK 64
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {

// Fused Marlin+EoRA rank-64 instantiation for dtype=bf16

template __global__ void MarlinEoraRank64<nv_bfloat16, vllm::kU4B8.id(), vllm::kBFloat16.id(), 256, 1, 8, 8, true, pipe_stages, 8, false>( MARLIN_EORA_KERNEL_PARAMS_FOR(nv_bfloat16) );

}
