// auto generated by generate_kernels.py
// clang-format off

#define MARLIN_KERNEL_FUNCTION MarlinLoraRank128
#define MARLIN_LORA_FUSED 1
#define MARLIN_LORA_RANK 128
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {

// Fused Marlin+LoRA rank-128 instantiation for dtype=bf16

template __global__ void MarlinLoraRank128<nv_bfloat16, vllm::kU4B8.id(), vllm::kBFloat16.id(), 256, 1, 8, 8, true, pipe_stages, 8, false>( MARLIN_LORA_KERNEL_PARAMS_FOR(nv_bfloat16) );

}
