// auto generated by generate_kernels.py
// clang-format off

#define MARLIN_KERNEL_FUNCTION MarlinEoraRank128
#define MARLIN_EORA_FUSED 1
#define MARLIN_EORA_RANK 128
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {

// Fused Marlin+EoRA rank-128 instantiation for dtype=fp16

template __global__ void MarlinEoraRank128<half, vllm::kU4B8.id(), vllm::kFloat16.id(), 256, 1, 8, 8, true, pipe_stages, 8, false>( MARLIN_EORA_KERNEL_PARAMS_FOR(half) );

}
